# Generated by Django 4.2.4 on 2023-08-03 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yuan_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrettyNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('price', models.IntegerField(default=0, verbose_name='价格')),
                ('level', models.SmallIntegerField(choices=[(1, '黑铁'), (2, '青铜'), (3, '黄金'), (4, '铂金'), (5, '钻石'), (6, '大师'), (7, '王者')], default=1, verbose_name='级别')),
                ('status', models.SmallIntegerField(choices=[(1, '已售出'), (2, '未使用')], default=2, verbose_name='状态')),
            ],
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='depart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yuan_app.department', verbose_name='部门'),
        ),
    ]
